### ISSUE TITLE
Agustin: working on making the Google Maps interactive to be able to click on it

### ISSUE THREAD

**Issue by eleqtrizit** [ZairaRiv/ESNS#4]
Not sure we're going to use Google Maps.  Might be easier with a png and some Javascript of our own.  This might be more amenable to heat maps on the map later.

**Comment by ZairaRiv** [comment]
How would the heat map help with the whole map situation?

**Comment by eleqtrizit** [comment]
I haven't thought it through.  I did find an Angular heatmap library already made.

https://www.patrick-wied.at/static/heatmapjs/

**Comment by ZairaRiv** [comment]
This method was going to be for clicking on the map directly, but I think that due to the sizes and other problems it is best that we use the drop down menu instead and leave this part out. The map on the first page should only display the data that is being pushed, and that data is coming from the report button.
Coincidentally, the report button is actually the link that will be sent to the student, not the main website page.
